### ISSUE TITLE
create possibility to delete data

### ISSUE THREAD

**Issue by michael-franke** [babe-project/BABE#18]
I would be good to be able to delete data sets. We often want to have a quick check if all data is recorded correctly, but we do not want to clutter the backend with many "*Test" or "*Dummy" entries.
Deletion should be possible, maybe after forcing the user to input the name of the experiment to make sure that deletion does not happen by accident.

**Comment by x-ji** [comment]
Sure. I was also thinking of adding this to the backend. Might have time to add it shortly.
