### ISSUE TITLE
Include check of DB address and server app status

### ISSUE THREAD

**Issue by michael-franke** [babe-project/BABE#32]
When posting experiments online, it CAN happen that the URL for data submission is incorrect. It might even happen that the server app is currently unresponsive (the server down, etc.). 

It would be good to check whether everything is setup correctly and working BEFORE participants start working on the experiment. Else, in case of a malfunction or mistake, participants' work is lost, generating extra overhead (time: apologies, setting up reimbursement HITs, rerunning experiment; cost: paying reimbursement HITs).

Ideally, in case of malfunction or mistake, the participants would immediately be told that there was an error (with an alert pop-up or an altert page) from which they cannot proceed. They would be told to return the HIT and contact the email supplied in 'config_deploy.js'. If possible, an automated email would also be good. 

This pre-check should be made for any submission method except 'debugMode'. (Not sure about  'localServer'?)

**Comment by x-ji** [comment]
Sure. So if I understand it correctly it would take two parts: one part on the server to return a message indicating whether the experiment with the indicated ID exists, and another part on the client to check for whether the server returns the correct message?

**Comment by michael-franke** [comment]
Yes, something along these lines.

**Comment by x-ji** [comment]
An automated email on the frontend is possible via some client-side error handling library. I might also just let the backend emit an error upon encountering such requests, which should be picked up by log monitoring services. However that wouldn't cover the situation of the server itself being down.
