### ISSUE TITLE
Release 0.1.0 not working with Ubuntu16

### ISSUE THREAD

**Issue by JannisBush** [babe-project/BABE#46]
I get the following error running `./babe console` on Ubuntu16.04:
```sh
jannis@UbuntuJ:~/babe_test/bin$ ./babe console
/home/jannis/babe_test/releases/0.0.1/babe.sh: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory
Unusable Erlang runtime system! This is likely due to being compiled for another system than the host is running
```

**Comment by x-ji** [comment]
Yeah as I suspected it might be easy for different Linux versions to be incompatible. I'll try to build it on a Ubuntu machine and see if it works. We can't possibly support all Linux systems though I guess supporting Ubuntu should be good enough.

**Comment by x-ji** [comment]
@JannisBush I added instructions for building a release into the README. Can you see if you can build a release on your system, and upload it to the repo? I might be able to try it out on a Ubuntu 16.04 system in a couple of days.

**Comment by JannisBush** [comment]
Thanks for the instructions.
I built and uploaded the release. 
It should work now.
