### ISSUE TITLE
Feature: Possibility to reset an experiment

### ISSUE THREAD

**Issue by JannisBush** [babe-project/BABE#54]
I can think of two use cases for the feature of resetting an experiment.

1. While creating/debugging complex experiments, it can happen that your submissions fail/have errors and therefore break your experiment, because you can't fetch the correct data from the server/older submissions. You then have to delete the experiment, create the same experiment again and change the ID in your configurations. Just resetting the experiment (clearing the submission data) would be easier. 

2. You carried out an experiment and retrieved the csv-data. You now want to redo the experiment with new participants. Currently, you have to create a new experiment with the same information and change the ID in the configurations. With a reset button, you could just start the experiment again. If the server adds a *global_iteration_number* field to the results table, you won't mix up the data from different repetitions of the experiment.

**Comment by x-ji** [comment]
Nice suggestion. I'll add a button for this.
