### ISSUE TITLE
Can't create complex experiments on the localServer

### ISSUE THREAD

**Issue by JannisBush** [babe-project/BABE#58]
Running the new `0.2.0` release of the localServer, I can't create complex experiments.
The following error occurs: 
> Server: localhost:4000 (http)
Request: POST /experiments
** (exit) an exception was raised:
    ** (ArgumentError) Cell-wise default values are not supported on INSERT statements by SQLite
        (sqlite_ecto2) lib/sqlite_ecto/connection.ex:155: anonymous fn/2 in Sqlite.Ecto2.Connection.insert_each/2
        (sqlite_ecto2) lib/sqlite_ecto/connection.ex:871: Sqlite.Ecto2.Connection.intersperse_reduce/5
        (sqlite_ecto2) lib/sqlite_ecto/connection.ex:146: anonymous fn/2 in Sqlite.Ecto2.Connection.insert_all/2
        (sqlite_ecto2) lib/sqlite_ecto/connection.ex:871: Sqlite.Ecto2.Connection.intersperse_reduce/5
        (sqlite_ecto2) lib/sqlite_ecto/connection.ex:145: Sqlite.Ecto2.Connection.insert_all/2
        (sqlite_ecto2) lib/sqlite_ecto/connection.ex:132: Sqlite.Ecto2.Connection.insert/6
        (sqlite_ecto2) lib/sqlite_ecto.ex:37: Sqlite.Ecto2.insert_all/7
        (ecto) lib/ecto/repo/schema.ex:52: Ecto.Repo.Schema.do_insert_all/7

Seems to be a problem of SQLite

**Comment by x-ji** [comment]
Thanks for reporting. I didn't test the new release enough. Please try using the dev mode with Postgres at the moment as I've written instructions in README. SQLite is quite different from Postgres in some aspects and I need to ensure that it works as well.

**Comment by x-ji** [comment]
@JannisBush I've pushed a new version that should fix it. Please give it a try under `:local` environment.

**Comment by JannisBush** [comment]
@x-ji Sorry for my late reply. I just tested it and it seems to work.

The repository, sql-branch and master branch, is already at 0.2.2, but we haven't uploaded this release yet. Maybe we should upload this version or 0.2.3, if there were any important changes after that.
