### ISSUE TITLE
protocal String.Chars not implemented for map

### ISSUE THREAD

**Issue by JannisBush** [babe-project/BABE#72]
I just tried to test [depaturePoint](https://github.com/babe-project/departure-point) using a local server and the babe-demo server and when I try to download the results an error occurs. 

On the babe-demo server you only see **Internal server error**, on the local server it says:
`
Protocol.UndefinedError at GET /experiments/1/retrieve
protocol String.Chars not implemented for %{"elemSize" => 15, "focalColor" => "blue", "focalNumber" => 23, "focalShape" => "circle", "otherColor" => "red", "otherShape" => "circle", "sort" => "random", "total" => 30}. This protocol is implemented for: Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Postgrex.Copy, Postgrex.Query, Time, URI, Version, Version.Requirement
`
I'm not sure if this is a problem with the backend or if we just use an unsupported datatype in the frontend/depaturePoint-demo.

**Comment by x-ji** [comment]
Does `departurePoint` work with the demo server? Apparently a whole JSON object is being submitted under one of the keys in the results object.

I think this is likely caused by the code from `babe-project` not running the function `flattenData` when the submission method is `localServer`. See `babe-submit.js`. Apparently nobody has tested/changed local submission related functionalities for a long while (this is also why tests are really important and we should definitely have enough tests on the frontend as well). I guess you should fix the issues related to `localServer` in the `babe-project` package.

**Comment by x-ji** [comment]
Though yeah if it also errors on the babe-demo server then it seems that the data format is not correct on both places. I'll take a look.

**Comment by x-ji** [comment]
Yes I think this is because the value of the key `"canvas"` is another JSON object, which is not allowed with the backend.

An example submission:

```json
{
  "f": "NA",
  "j": "NA",
  "RT": "NA",
  "QUD": "NA",
  "age": "",
  "key1": "NA",
  "key2": "NA",
  "rows": "NA",
  "sort": "random",
  "total": 30,
  "canvas": {
    "sort": "random",
    "total": 30,
    "elemSize": 30,
    "focalColor": "green",
    "focalShape": "triangle",
    "otherColor": "green",
    "otherShape": "square",
    "focalNumber": 10
  },
  "gender": "",
  "endTime": 1551271652928,
  "option1": "Yes",
  "option2": "No",
  "picture": "NA",
  ...
```

One should flatten the value under this `"canvas"` key as well, or should the server try to flatten it if such a submission actually gets through?

**Comment by JannisBush** [comment]
I could flatten the values under the `"canvas"` key and also add a warning on the front-end, that custom views should only use flat trial records. 

In the "Additional Notes" section it is written that it would be hard to create a correct csv-file, but if it is possible it might be nice to allow non flat trial records, because users might want to use them in their custom views (e.g. a drop-down task with a variable number of choices). 
We could either try to flatten all records in the front-end, in the back-end or try to allow flexible structures, like arrays, without flattening them.

**Comment by JannisBush** [comment]
The values under the `canvas`-key are now flattened correctly in the view templates https://github.com/babe-project/babe-project/pull/35.
I guess, we can continue to tell our users to only use flat data in their custom views.

**Comment by x-ji** [comment]
:+1:
